// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAufpUFKjhJnTks_SeBqyvygFMeGVSuvds',
    appId: '1:140419312313:web:6abedd0c409329a35c0968',
    messagingSenderId: '140419312313',
    projectId: 'chatkaro-8d37d',
    authDomain: 'chatkaro-8d37d.firebaseapp.com',
    storageBucket: 'chatkaro-8d37d.firebasestorage.app',
    measurementId: 'G-KP95D74310',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIICKRT8hCkz9BK8ch9C7VQnedCOWlYoA',
    appId: '1:140419312313:android:0a36ba88c1b78e595c0968',
    messagingSenderId: '140419312313',
    projectId: 'chatkaro-8d37d',
    storageBucket: 'chatkaro-8d37d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA_QF3fgD1bo7bu3mH3htbQqUdkhhgjNM',
    appId: '1:140419312313:ios:e9fb1891bcaa92705c0968',
    messagingSenderId: '140419312313',
    projectId: 'chatkaro-8d37d',
    storageBucket: 'chatkaro-8d37d.firebasestorage.app',
    iosBundleId: 'com.example.chatkaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA_QF3fgD1bo7bu3mH3htbQqUdkhhgjNM',
    appId: '1:140419312313:ios:e9fb1891bcaa92705c0968',
    messagingSenderId: '140419312313',
    projectId: 'chatkaro-8d37d',
    storageBucket: 'chatkaro-8d37d.firebasestorage.app',
    iosBundleId: 'com.example.chatkaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAufpUFKjhJnTks_SeBqyvygFMeGVSuvds',
    appId: '1:140419312313:web:ee5f6ea988a5232e5c0968',
    messagingSenderId: '140419312313',
    projectId: 'chatkaro-8d37d',
    authDomain: 'chatkaro-8d37d.firebaseapp.com',
    storageBucket: 'chatkaro-8d37d.firebasestorage.app',
    measurementId: 'G-8HGCZFFWH9',
  );
}
